cegui/src/IconvStringTranscoder.cpp: use cast notation instead of reinterpret_cast
Fixes:
	IconvStringTranscoder.cpp:50:49: error: invalid cast from type 'int' to
	type 'iconv_t' {aka 'long int'}
         if (d_cd == reinterpret_cast<iconv_t>(-1))

Signed-off-by: Bartosz Bilas <b.bilas@grinn-global.com>